# Generated by Django 3.0.3 on 2020-03-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='dolist',
        ),
    ]
