# Generated by Django 3.0.3 on 2020-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20200320_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolist',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
